# Generated by Django 6.0.6 on 2026-06-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Ram',
        ),
    ]
