# Generated by Django 5.2.15 on 2026-06-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('meal_type', models.CharField(choices=[('', 'Brealfast')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('prepare_time', models.PositiveIntegerField(help_text='Enter time in minetus')),
            ],
            options={
                'db_table': 'meal',
            },
        ),
        migrations.AlterModelTable(
            name='mealplan',
            table='meal plan',
        ),
        migrations.CreateModel(
            name='Meal_Plane_Itmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealplan')),
            ],
            options={
                'db_table': 'meal plane itmes',
            },
        ),
    ]
