# Generated by Django 5.2.15 on 2026-06-22 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_alter_mealplan_table_meal_plane_itmes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.RenameModel(
            old_name='MealPlan',
            new_name='Meal_Plan',
        ),
        migrations.RenameModel(
            old_name='Meal_Plane_Itmes',
            new_name='Meal_Plan_Items',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('BreakFast', 'Brealfast'), ('Lunch', 'Lunch'), ('Snakes', 'Snacks'), ('Dinner', 'Dinner')], max_length=20),
        ),
        migrations.CreateModel(
            name='Meal_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
            options={
                'db_table': 'meal_ingredient',
                'unique_together': {('meal', 'ingredient')},
            },
        ),
    ]
