# Generated by Django 5.2.15 on 2026-07-01 02:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_ingredient_rename_mealplan_meal_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal_Ingredients',
            new_name='MealIngredients',
        ),
        migrations.RenameModel(
            old_name='Meal_Plan',
            new_name='MealPlan',
        ),
        migrations.RenameModel(
            old_name='Meal_Plan_Items',
            new_name='MealPlanItems',
        ),
        migrations.AlterModelTable(
            name='mealingredients',
            table='meal ingredient',
        ),
    ]
