# Generated by Django 5.2.15 on 2026-07-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_rename_meal_ingredients_mealingredients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealIngredients',
            new_name='MealIngredient',
        ),
    ]
