# Generated by Django 5.2.15 on 2026-06-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='items',
            table='Things',
        ),
    ]
