# Generated by Django 5.2.15 on 2026-06-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_items_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
