# Generated by Django 5.2.15 on 2026-07-13 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Activate', 'Activate'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Paused', 'Paused'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserSubscriptions', to='plan.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='khalti', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Sucess'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pidx', models.CharField(blank=True, max_length=50, null=True)),
                ('Subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='plan.usersubscription')),
            ],
        ),
    ]
