# Generated by Django 5.2.15 on 2026-07-13 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_usersubscription_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Subscription',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='duration_day',
            new_name='duration_days',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='start_data',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='plan.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Paused', 'Paused'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='subscription plan',
        ),
        migrations.AlterModelTable(
            name='usersubscription',
            table='user subscription',
        ),
    ]
